name: ci

permissions: {}

on: [push, pull_request]

jobs:
  ci:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🚧 Set up project
        run: pnpm nuxi prepare

      - name: 📝 Lint
        run: pnpm lint

      - name: 💪 Type check
        run: pnpm typecheck
