name: build, push & deploy docker container

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.metal.outputs.version }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: metal
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/np-inprove/app

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metal.outputs.tags }}
          labels: ${{ steps.metal.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    if: github.event_name != 'pull_request'
    runs-on: self-hosted
    needs: docker
    permissions:
      packages: read

    steps:
      - name: Pull latest image
        run: podman pull ghcr.io/np-inprove/app:${{ needs.docker.outputs.version }}

      - name: Stop previous container
        run: podman stop app && podman rm app || echo "Stopping previous container..."

      - name: Start new container
        run: podman run -p 3000:3000 --name app -d ghcr.io/np-inprove/app:${{ needs.docker.outputs.version }}

      - name: Clear unused images
        run: podman rmi $(podman images -f "dangling=true" -q)
